export const PRODUCTS_LOADING = 'PRODUCTS_LOADING';
export const ADD_PRODUCTS = 'ADD_PRODUCTS';
export const PRODUCTS_FAILED = 'PRODUCTS_FAILED';

export const CAROUSELS_LOADING = 'CARSOUSELS_LOADING';
export const ADD_CAROUSELS = 'ADD_CAROUSELS';
export const CAROUSELS_FAILED = 'CAROUSELS_FAILED';